# Site settings
baseurl = "https://nuscomputing.com/"
languageCode = "en-us"
title = "NUS Students' Computing Club"
theme = "hugo-agency-theme"
publishDir = "docs"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Computing Club"
  description = "We are the official student club of NUS School of Computing. We plan events for the undergraduate student body and ensure that students' welfare is taken care of. We organise fun social activities, games, sports and camps to complement the rigourous coursework that students go through daily."


  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"


  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false


  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"


  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="


  # Navigation
  [params.navigation]
    brand = "NUS Computing"
    # Optional logo as brand stored in img/
    logo = "logos/nuscomputing.png"
    services = "Services"
    events = "Events"
    about = "About"
    team = "Team"
    sponsors = "Sponsors"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "mailto:connect@nuscomputing.com"
      name = "Contact"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Freshmen Orientation Program"
    subtitle = "OHH Recruitment"
    buttonText = "Learn more"
    buttonLink = "#events"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "The Computing Club manages the following services and portals."

    [[params.services.row]]

      [[params.services.row.list]]
        icon = "fa-graduation-cap"
        title = "Academic Liaison"
        description = "For students who need help with their studies or are confuse with the academic administration."
        url = "https://acad.nuscomputing.com/"

      [[params.services.row.list]]
        icon = "fa-calendar"
        title = "Noticeboard"
        description = "For members who want to keep track with the latest events happening in SoC."
        url = "https://noticeboard.nuscomputing.com/"

      [[params.services.row.list]]
        icon = "fa-users"
        title = "FOP"
        description = "For incoming freshman who wants to find out more about the school or to make friends and have fun."
        url = "https://freshmen.nuscomputing.com/"


  # Events section
  [params.events]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Events"
    description = "The Computing Club organises events for its members to help create bonds and foster a sense of family between its members. We urge all club members to come down for our events and mingle with your fellow students!"

    [params.events.modal]
      sponsor = "sponsor"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


  # About section
  [params.about]
    enable = false
    title = "About"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    endpoint = "Be part<br>of our<br>story!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "2009-2011"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "2.jpg"
      date = "March 2011"
      title = "An Agency is Born"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "3.jpg"
      date = "December 2012"
      title = "Our Humble Beginnings"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    [[params.about.events]]
      img = "4.jpg"
      date = "July 2014"
      title = "Phase Two Expansion"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = false
    title = "20th Management Committee"
    description = "Throughout a typical academic year, we organizes various events for its members. There are camps specially designed to assist the incoming freshmen, collaborations with the professors to provide addtional assistance to the weaker students, parties for our members who are graduating and many more events! Browse through the website for more information regarding our events and initiatives."
    wings = [ "Presidential Wing", "Student Life", "External Relations", "Internal Relations", "Student Development" ]

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "JoelLim.jpg"
      name = "Joel Lim"
      position = "President"
      wing = "Presidential Wing"

    [[params.team.members]]
      img = "TsaiYuHsuan.jpg"
      name = "Tsai Yu Hsuan"
      position = "General Secretary"
      wing = "Presidential Wing"

    [[params.team.members]]
      img = "NgCheeSiang.jpg"
      name = "Ng Chee Siang"
      position = "Assistant General Secretary"
      wing = "Presidential Wing"

    [[params.team.members]]
      img = "JasonYip.jpg"
      name = "Jason Yip"
      position = "Finance Secretary"
      wing = "Presidential Wing"

    [[params.team.members]]
      img = "LeeShiMing.jpg"
      name = "Lee Shi Ming"
      position = "Assistant Finance Secretary"
      wing = "Presidential Wing"

    [[params.team.members]]
      img = "EugeneLim.jpg"
      name = "Eugene Lim"
      position = "IT Secretary"
      wing = "Presidential Wing"

    [[params.team.members]]
      img = "ChngZhiXuan.jpg"
      name = "Chng Zhi Xuan"
      position = "Assistant IT Secretary"
      wing = "Presidential Wing"

    [[params.team.members]]
      img = "YeoKianWee.jpg"
      name = "Yeo Kian Wee"
      position = "Vice President (External Relations)"
      wing = "External Relations"

    [[params.team.members]]
      img = "LawrenceLim.jpg"
      name = "Lawrence Lim"
      position = "Director of Publicity"
      wing = "External Relations"

    [[params.team.members]]
      img = "RebeccaTan.jpg"
      name = "Rebecca Tan"
      position = "Deputy Director of Publicity"
      wing = "External Relations"

    [[params.team.members]]
      img = "GervaiseAng.jpg"
      name = "Gervaise Ang"
      position = "Director of Marketing"
      wing = "External Relations"

    [[params.team.members]]
      img = "KevinAlvarez.jpg"
      name = "Kevin Alvarez"
      position = "Deputy Director of Marketing (Sponsorship)"
      wing = "External Relations"

    [[params.team.members]]
      img = "ClarisseLim.jpg"
      name = "Clarisse Lim"
      position = "Deputy Director of Marketing (Merchandise)"
      wing = "External Relations"

    [[params.team.members]]
      img = "AmandaTan.jpg"
      name = "Amanda Tan"
      position = "Vice President (Internal Relations)"
      wing = "Internal Relations"

    [[params.team.members]]
      img = "IanTan.jpg"
      name = "Ian Tan"
      position = "Director of Welfare"
      wing = "Internal Relations"

    [[params.team.members]]
      img = "LowRuiJia.jpg"
      name = "Low Rui Jia"
      position = "Deputy Director of Welfare"
      wing = "Internal Relations"

    [[params.team.members]]
      img = "ShannonKok.jpg"
      name = "Shannon Kok"
      position = "Director of Sports"
      wing = "Internal Relations"

    [[params.team.members]]
      img = "KerwinKow.jpg"
      name = "Kerwin Kow"
      position = "Deputy Director of Sports"
      wing = "Internal Relations"

    [[params.team.members]]
      img = "ElysiaTan.jpg"
      name = "Elysia Tan"
      position = "Vice President (Student Development)"
      wing = "Student Development"

    [[params.team.members]]
      img = "LeeYiyuan.jpg"
      name = "Lee Yiyuan"
      position = "Director of Academic Liaison"
      wing = "Student Development"

    [[params.team.members]]
      img = "GabrielTan.jpg"
      name = "Gabriel Tan"
      position = "Deputy Director of Academic Liaison"
      wing = "Student Development"

    [[params.team.members]]
      img = "TanWeiLi.jpg"
      name = "Tan Wei Li"
      position = "Director of Community Service"
      wing = "Student Development"

    [[params.team.members]]
      img = "ZhaoJunRu.jpg"
      name = "Zhao Jun Ru"
      position = "Deputy Director of Community Service"
      wing = "Student Development"
      
    [[params.team.members]]
      img = "JoelSim.jpg"
      name = "Joel Sim"
      position = "Vice President (Student Life)"
      wing = "Student Life"

    [[params.team.members]]
      img = "VanessaLoh.jpg"
      name = "Vanessa Loh"
      position = "Director of Freshmen Orientation Projects"
      wing = "Student Life"

    [[params.team.members]]
      img = "FrancisLee.jpg"
      name = "Francis Lee"
      position = "Deputy Director of Freshmen Orientation Projects"
      wing = "Student Life"

    [[params.team.members]]
      img = "LimSingJie.jpg"
      name = "Lim Sing Jie"
      position = "Director of Student Relations"
      wing = "Student Life"

    [[params.team.members]]
      img = "JeremyLim.jpg"
      name = "Jeremy Lim"
      position = "Deputy Director of Student Relations"
      wing = "Student Life"


  # Sponsor section
  [params.sponsors]
      enable = true
      # Possibility to center items
      center = true
      # Optional sponsor title specifying the involvement
      title = "Sponsors"
      description = "We would like to thank our sponsors for supporting our events and believing in us throughout the years. We hope to continue this beneficial working relationship with our sponsors and hope to forge more relationships with organisations that may want to support us as well. Please contact us at connect{at}nuscomputing{dot}com if you would like to be a supporter for our future events!"

      # All the sponsors' logos are stored under 'static/img/logos'.
      # Replace them with your sponsors's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.sponsor]]
        logo = "300-positive.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "90s-candy-society.png"
        link = "#"

      [[params.sponsor]]
        logo = "accenture.png"
        link = "#"

      [[params.sponsor]]
        logo = "aptus.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "atlantic-optical.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "ban-choon.png"
        link = "#"

      [[params.sponsor]]
        logo = "bnp-paribas.png"
        link = "#"

      [[params.sponsor]]
        logo = "botak-jones.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "bubble-bump.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "chat.png"
        link = "#"

      [[params.sponsor]]
        logo = "crimsonlogic.png"
        link = "#"

      [[params.sponsor]]
        logo = "csit.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "dso.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "forest-adventure.png"
        link = "#"

      [[params.sponsor]]
        logo = "glints.png"
        link = "#"

      [[params.sponsor]]
        logo = "gogo-van.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "gumtree.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "happi.png"
        link = "#"

      [[params.sponsor]]
        logo = "im-kim.png"
        link = "#"

      [[params.sponsor]]
        logo = "ippin.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "jetaime.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "jetbrains.png"
        link = "#"

      [[params.sponsor]]
        logo = "kokomama.png"
        link = "#"

      [[params.sponsor]]
        logo = "laffio.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "matchaya.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "mgp.png"
        link = "#"

      [[params.sponsor]]
        logo = "milkcow.png"
        link = "#"

      [[params.sponsor]]
        logo = "paper-innovation.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "playnation.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "pokka.png"
        link = "#"

      [[params.sponsor]]
        logo = "shopback.png"
        link = "#"

      [[params.sponsor]]
        logo = "singapore-pub-crawl.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "singapore-world-water-day.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "sta-travel.png"
        link = "#"

      [[params.sponsor]]
        logo = "the-manhattan-fish-market.png"
        link = "#"

      [[params.sponsor]]
        logo = "triple-dry.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "uber.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "viewqwest.png"
        link = "#"

      [[params.sponsor]]
        logo = "woods.png"
        link = "#"

      [[params.sponsor]]
        logo = "yakult.png"
        link = "#"
      
      [[params.sponsor]]
        logo = "zalora.png"
        link = "#"

      [[params.sponsor]]
        logo = "zookal.png"
        link = "#"


  # Contact section
  [params.contact]
    enable = false
    title = "Contact us"
    subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"


  # Footer section
  [params.footer]
    enable = true
    copyright = "Made with ‚ù§ by NUSComputing"

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/NUSCompClub"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/NUSComputing"
    
    [[params.footer.social]]
      icon = "fa-instagram"
      link = "http://instagram.com/NUSComputingClub"
    
    [[params.footer.social]]
      icon = "fa-youtube"
      link = "https://www.youtube.com/channel/UCVd-qsSFF328UUqcNxudy0w"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "https://www.linkedin.com/company/NUSComputing"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/NUSComputingDev"
